version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-config/rules.yml:/etc/prometheus/rules.yml
      - ./prometheus-data:/prometheus
    networks:
      - localnetwork
    ports:
      - 9090:9090
 
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - localnetwork
    ports:
      - 9100:9100
 
  alert-manager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - localnetwork
    ports:
      - 9093:9093
 
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
     - 8080:8080
    networks:
      - localnetwork
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    ports:
    - 3000:3000
    networks:
      - localnetwork
    volumes:
    - ./grafana-data:/var/lib/grafana
    depends_on:
    - prometheus
 
networks:
  localnetwork:
    driver: bridge