groups:
- name: instance-down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 20s
 
- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."
 
- name: host
  rules:
  - alert: HighMemoryLoad
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."
 
- name: containers
  rules:
  - alert: PHP_FPM_Down
    expr: absent(container_memory_usage_bytes{name="project-report-php-fpm"})
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "PHP-FPM Container is Down"
      description: "PHP-FPM container is down for more than 30 seconds."
 
  - alert: MySQL_Down
    expr: absent(container_memory_usage_bytes{name="project-report-mysql"})
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "MySQL Container is Down"
      description: "MySQL container is down for more than 30 seconds."